name: Deploy Taiga

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Decode and set up the SSH private key
    - name: Decode and Set Up SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > key.pem
        chmod 600 key.pem

    # Step 3: Test SSH connection to the EC2 instance
    - name: Test SSH Connection
      run: ssh -i key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} hostname

    # Step 4: Deploy Taiga using SSH
    - name: Deploy Taiga via SSH
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ./key.pem
        script: |
          cd taiga
          git pull origin main
          ./launch-all.sh